name: Run JMeter tests

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: '0 12 * * 5'  # Every Friday at 12am UTC

jobs:
  jmeter-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Download and extract JMeter
        run: |
          wget https://downloads.apache.org/jmeter/binaries/apache-jmeter-5.6.3.tgz
          tar -xzf apache-jmeter-5.6.3.tgz


      - name: Install Robot Framework + Selenium
        run: |
            pip install robotframework
            pip install robotframework-seleniumlibrary
            pip install robotframework-yamllibrary
            pip install robotframework-csvlib
            pip install robotframework-excellibrary
            pip install robotframework-jsonlibrary
            pip install selenium
            wget https://chromedriver.storage.googleapis.com/114.0.5735.90/chromedriver_linux64.zip
            unzip chromedriver_linux64.zip
            sudo mv chromedriver /usr/local/bin/

      - name: Install Chrome (for Selenium)
        run: |
            sudo apt-get update
            sudo apt-get install -y google-chrome-stable
        
      - name: Create results and report directories
        run: |
          mkdir -p tests/results
          mkdir -p tests/report
      
      - name: Set up JMeter
        run: |
            sudo apt-get update
            sudo apt-get install -y jmeter

      - name: Run JMeter test
        run: |
          apache-jmeter-5.6.3/bin/jmeter -n -t "tests/jmx/SurveyResponse_FNB.jmx" -l tests/results/results.jtl -j tests/results/jmeter.log

      - name: Run Robot Framework tests
        run: |
            robot --outputdir results tests/JM_FNB.robot

      - name: Generate HTML report
        run: |
          apache-jmeter-5.6.3/bin/jmeter -g tests/results/results.jtl -o report

      - name: List result files for debug
        run: |
          echo "=== JTL ==="
          ls -lh tests/results/
          echo "=== Report ==="
          ls -lh tests/report/

      - name: Upload JTL results
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-jtl-results
          path: tests/results/results.jtl

      - name: Upload HTML report
        uses: actions/upload-artifact@v4
        with:
          name: jmeter-html-report
          path: tests/report
